---
- name: Create a GCP VM
  hosts: localhost
  gather_facts: false
  vars:
    gcp_project_id: "{{ lookup('env', 'GOOGLE_CLOUD_PROJECT') }}"
    gcp_cred_kind: "serviceaccount"
    gcp_cred_file: "creds.json"
    gcp_region: "europe-west1"
    gcp_zone: "{{ gcp_region }}-b"
    vm_name: "ansiblevm"
    vm_machine_type: "e2-standard-2"
    vm_image_project: "rhel-cloud"
    vm_image_family: "global"
    vm_network_name: "default"
    vm_subnetwork_name: "default"
  tasks:

  - debug:
      var: gcp_project_id

  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/rhel-cloud/global/images/rhel-8-v20230202
      zone: europe-west1-b
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{  gcp_cred_file  }}"
      state: present
    register: disk

  - name: create a instance
    google.cloud.gcp_compute_instance:
      name: testvm
      machine_type: e2-standard-2
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      labels:
        environment: production
      network_interfaces:
      - network: null
        access_configs:
        - name: External NAT
          type: ONE_TO_ONE_NAT
      metadata:
        items:
        - key: startup-script
          value: "{{ lookup('file', 'startup-script.sh') }}"
      zone: europe-west1-b
      project: "{{ gcp_project_id }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{  gcp_cred_file  }}"
      state: present




